### ISSUE TITLE
Stake W/ Any Token (Contract Dev Only)

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/Ecosystem#15]
# Description
In DAOstack's Holographic Consensus protocol, you can stake on proposals with the GEN token. More info on how this works can be found [here](https://medium.com/daostack/holographic-consensus-part-1-116a73ba1e1c).

It would be great if users of [Alchemy](https://alchemy.daostack.io) could stake on proposals with any token. Upon staking with a token that isn't GEN, your token would be automatically swapped (using Uniswap or KyberSwap) into GEN, and that GEN would be staked on the proposal. When the user redeems, they could choose to either redeem with GEN or get their original token back.

NOTE: slippage is a thing, and if GEN goes down during the time they're staked in, they'd be at a loss on their initial investment, but could make more back if they make more GEN.

# Potential Implementation
`Note: This is only an initial stab at what the implementation might look like, creative freedom is encouraged!`
1. Create a wrapper contract called `SwapAndStake`.
2. Expose functions `stakeERC20` and `stakeETH`.
3. Swap incoming tokens (Uniswap only support for now is fine).
4. Stake resulting GEN on the proposal.
  * In order to do (4) on behalf of the user, this contract would need to be approved by the user. This may make `stakeETH` impossible to implement in a single function, but WETH could be used. There is also a `stakeWithSignature` function that could be used :thinking:

# Relevant Code
Uniswap: https://github.com/Uniswap/contracts-vyper
GenesisProtocol Stake Method: [link](https://github.com/daostack/infra/blob/9b45fc0eb86ee3043f1eb838cb8504cdb7b5947e/contracts/votingMachines/GenesisProtocol.sol#L43)
GenesisProtocol StakeWithSignature Method: [link](https://github.com/daostack/infra/blob/9b45fc0eb86ee3043f1eb838cb8504cdb7b5947e/contracts/votingMachines/GenesisProtocol.sol#L61)
ERC20: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol

# Funding
$600 [Proposal Passed](https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526/proposal/0x7e39e0c48f6ed17d955b887de76d826dd747ab97e9619d3fa5314833a88a5874)

**Comment by orishim** [comment]
Related / same: https://github.com/daostack/Ecosystem/issues/1

**Comment by benefacto** [comment]
Hey @dOrgJelli, by Contract Dev Only, do you mean this bounty is only available to an individual who has already completed the [agent onboarding process](https://docs.dorg.tech/working-together/admin#on-boarding) or can anyone pick it up?

**Comment by dOrgJelli** [comment]
Hey @benefacto, sorry for the confusion, "Contract" in this case refers to "Smart Contract". This means that the solution proposed here is intended to be a smart contract solution that swaps the input token to GEN and stakes it on a proposal.

**Comment by dOrgJelli** [comment]
Here's the "UI Only" version of this: https://github.com/daostack/Ecosystem/issues/1

The problem can be solved in 2 ways, the smart contract solution proposed above, or a UI wrapper that makes it easier for users to buy/swap & stake GEN on proposals.

**Comment by benefacto** [comment]
Awesome, thanks for the clarification!

**Comment by orishim** [comment]
Proposing we close this for now. Could be re-opened for DAOstack funding as an [Alchemy RFC](https://github.com/dOrgTech/Ecosystem/tree/master/proposals/Alchemy).

**Comment by dOrgJelli** [comment]
I agree with this @orishim
