### ISSUE TITLE
dOrg REP Distribution Simulation + Visualization

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/Ecosystem#19]
# Description
Create a simple interface that:
1. Looks up the current DAO reputation holders
2. Plots them on a two dimensional graph { Y == REP, X == Time, Line == Agent's REP }
3. Have an input box for "monthly earnings" (default everyone to $7,500).
4. Simulate the reputation distribution into the future, plotting the lines in the positive X direction.
5. Allow the user to edit monthly earnings.

Bonus points if you can add new members.

**Comment by orishim** [comment]
Another visualization approach is a pie chart that shows the current Rep distribution and then you can run the simulation and see the pie chart change over time.

![Rep Simulation](https://user-images.githubusercontent.com/10736693/67481812-428d4980-f66b-11e9-8109-af100422f818.png)
