### ISSUE TITLE
Replicate our landing page using Gatsby

### ISSUE THREAD

**Issue by orishim** [dOrgTech/Ecosystem#23]
Currently the landing page is implemented as additional screens inside of the DAOcreator app. We'd like to a) separate the landing page into a different repo (dOrgTech/DAOcreator#11) and b) move to the [Gatsby framework](https://www.gatsbyjs.org) to have an easily editable, markdown driven site.

Additional improvements are also welcome, such as:
- Representing each 'Case' as its own markdown file that can be expanded to show more information, such as a longer description with screenshots
- New sections, such as 'Members' or 'Media Mentions'

# Funding Request
$350 - $600

**Comment by alarivan** [comment]
dOrg landing repository with Gatsby: https://github.com/alarivan/dorg-landing

I worked with @orishim and @dOrgJelli to complete this project.

Requested funds: $500

ETH: 0x1f134294dEE0055Da2a9914f73D2a7A59D374AC0

**Comment by dOrgJelli** [comment]
I vouch for the work done here by @alarivan. He's...
- Created a Gatsby boilerplate and modified it to our needs
- Added our existing React + Material-UI site
- Converted our "Cases" and "About" sections of the site to be data-driven through markdown files, allowing us to iterate and add content much faster.
- Added mdxjs support
- Is open to consulting us in the future of the site, where we might want to use a CMS for our content, and introduce new views for added content.

**Comment by dOrgJelli** [comment]
Submission Proposal: https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526/proposal/0xb62e030775a4e95b5e62c6b123e903a788e02debc2a63d60d4b07d762535bc42
