### ISSUE TITLE
Modeling & Upgrading dOrg Payment/Rep/Token dynamics

### ISSUE THREAD

**Issue by orishim** [dOrgTech/Ecosystem#24]
# Description 

dOrg currently achieves naive meritocracy through a simple fund and Rep distribution scheme, whereby:
- one global [`FTE-rate`](https://dorg.gitbook.io/-/our-organization/understanding-compensation) bounds a player's monthly earnings (e.g. $7500) and
- one global [`rep-rate`](https://dorg.gitbook.io/-/our-organization/understanding-rep) defines the ratio of Rep minted per dollar equivalent earnings (e.g. 1 Rep per $200).

While elegant and meritocratic, this one-dimensional scheme might not scale well for a dynamic, multi-stakeholder group. 

An ideal scheme would align the interests of
- Different types of freelancers {devs // designers // facilitators // advisors // recruitment // sales}
- Partners & 3rd-party service providers? {lawyers // accountants // external dev shops}
- Customers?
- Investors?

One approach is to begin utilizing the dOrg DAO's erc-20 token– potentially with added dividend functionality– to give long-term stakeholders un-slashable financial upside in the entity's success. This would create complementary roles for Rep (controls voting weight, non-transferrable, minted and burned by the DAO) and Token (transferrable, only minted by the DAO).

# Possible Implementation

Specify the new scheme in a markdown file and embed useful diagrams. Make sure to get feedback from active dOrg members before final submission!

### Bonus
Use [cadCAD](https://pypi.org/project/cadCAD/) python based modeling framework or similar tools to test and support your hypotheses.

**Comment by orishim** [comment]
Taking inspiration from [this article](https://www.placeholder.vc/blog/2019/10/6/protocols-as-minimally-extractive-coordinators), I'd like to rethink dOrg as a protocol for freelance work coordination.

Protocols, as opposed to companies, allow anyone to participate and utilize market dynamics to automate price discovery. As a result, they benefit from network effects, avoid discrimination, and minimize unnecessary value extraction.

In this model there are three types of actors:

| Actor | Description | Compound (example) | Bitcoin (example) | dOrg |
|-|-|-|-|-|
| Suppliers | Produce the discrete service that the protocol specializes in | Lenders | Miners | Freelancers |
| Consumers | Pay to use the protocol’s services | Borrowers | Users | Customers |
| Distributors | Help deliver the service to the consumer by bundling extra layers of support (not required for every consumer) | InstaDApp | Coinbase | Facilitators? |

I think the key questions for dOrg to explore are how we coordinate freelancer, customer, facilitator interactions through
1. Payment Mechanics
2. Token/Rep Distribution

**Comment by dOrgJelli** [comment]
I think an added definition that's needed is "what is dOrg" in the future? Is it only ever a single DAO of freelancers? Is it also a protocol for freelancer coop networks? Is it an application that gives access to that protocol?

My own opinion:
dOrg is currently just a DAO, but should give birth to a protocol for many DAOs to coordinate for the sake of supporting next-gen freelancing. In this model you have (1) dOrg DAO [us now, the initial "experiment"] (2) dOrg Protocol (3) dOrg Enabled dApp

**Comment by dOrgJelli** [comment]
Re: Dividend Bearing Token - I like the idea of starting small with no public market maker (bonding curve), and instead just doing the simple (1) DAO mints dOrg token via proposal (2) DAO allocates dividends to token holders via proposal. This simple approach would essentially be for internal use only, and could evolve into a public market that has control of minting these tokens. If we do this first approach before the bonding curve, we'd need to understand how the transition would happen.

**Comment by orishim** [comment]
Updating the chart to reflect your point from the first comment:

| Actor | dOrg |
|-|-|
| Suppliers | Freelancer Agencies, such as dOrg |
| Consumers | Customers |
| Distributors | Friendly apps that connect Customers with Freelancer Agencies and bundle in other services like project management, customer service, legal, bookkeeping |

**Comment by orishim** [comment]
See updated payment/rep/token dynamics here:
https://docs.dorg.tech/getting-started-1/form-and-function#sustenance-and-governance
