### ISSUE TITLE
Proposal Scheduler

### ISSUE THREAD

**Issue by orishim** [dOrgTech/Ecosystem#28]
# Description

A service for scheduling a set of proposals to be automatically submitted in the future. We'd run this service on a server with a wallet that has some gas to make the proposal submissions at the scheduled times.

This is how the input might look as a json:
```
[
    {
        "DAO" : "0xbe1a98d3452f6da6e0984589e545d4fc25af7526",
        "Scheme" : "0x82523f624c8b894c2726ffec1064794b77e35a44c89f554d54e3bc4b595da81b",
        "Fields" : {
            "Title" : "Recurring payment proposal to Alice",
            "Description" : "2019 Q4 bimonthly payments from dOrg to Alice for software development services",
            "URL" : "https://github.com/dOrgTech/Ecosystem/tree/master/proposals/Alice_Recurring_Proposal.md",
            "Recipient" : "0x0aED75D4559370c974BD8D827efE9E4BdD2A4517",
            "ETH Reward" : "0",
            "Reputation Reward" : "10",
            "External Token Reward" : {
                "Token Address" : "0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359",
                "Amount" : "2000"
            },
            "DAO Token Reward" : "0" 
        },
        "Schedule" : [
            1571097600,
            1572480000,
            1573776000,
            1575072000,
            1576368000,
            1577750400
        ]
    },
    {
        "DAO" : "...",
        "Scheme" : "...",
        "Fields" : {
            ...
        },
        "Schedule" : [
            ...
        ]
    },
    ...
    ...
]
```
A U.I. could also be developed to make the creation of these json's easier.

# Impact
This would be incredibly helpful for repetitive tasks, such as:
- bimonthly freelancer payment proposals to dOrg DAO
- monthly dOrg funding proposals to Genesis DAO

Such a service could also be extended to support dynamic inputs, such as checking a price feed to adjust the amount of ETH being asked for.

**Comment by orishim** [comment]
Related as this would probably make the transaction calls easier:
https://github.com/daostack/alchemy/issues/1181

**Comment by shivgupt** [comment]
This is good if you want an ability to cancel the payments in middle. But if the contract is already signed for x-months/weeks and there won't be cancellation mid way, I would suggest to consider the alternative as described below.

A bimonthly/monthly pay can be achieved via specifying periods in contribution reward. 

The 4th parameter of the `proposeContributionReward` is a `uint[5] _rewards` array, where the details for this array are these.

```
rewards[0] - Amount of tokens requested per period
rewards[1] - Amount of ETH requested per period
rewards[2] - Amount of external tokens requested per period
rewards[3] - Period length - if set to zero it allows immediate redeeming after execution.
rewards[4] - Number of periods
```

If a non-zero period length (reward[3]) is specified then at each the start of each period the beneficiary can redeem the rewards.

The following exists at the arc layer and can be pretty easily be enabled in Alchemy UI.
