### ISSUE TITLE
Fiat On-Ramp

### ISSUE THREAD

**Issue by orishim** [dOrgTech/Ecosystem#29]
## Problem

A fiat on-ramp for clients to pay our DAO through bank transfers.

Even though we only deal with crypto companies currently, most still prefer to pay consultants through good ole bank transfers. If we ever want to expand to non-crypto savvy clients (non-profits, corporates) this will be a necessity.

## Solutions

Add a "Payments" page to the dOrg website that uses a 3rd-party fiat on-ramp integration. Clients can simply be directed to this page to pay us.

The 3rd party on-ramp must be able to support direct payments to our DAO's address– NOT some virtual wallet on their system which some privileged admin in dOrg needs to withdraw to our DAO.

*Options:*

- [Wyre](https://www.sendwyre.com)
    - Easily embeddable web module
    - Uses [Plaid](https://plaid.com/); Bank transfers from Europe, Canada, US
    - Supports DAI & Ethereum
- [CoinDirect](https://www.coindirect.com/business/buy-crypto)
    - Bank transfers from Europe & Africa, Credit cards from anywhere, Mobile Money from Africa
    - No fee, just a spread on buys
    - Supports Ethereum
- [CoinAcquiring](https://coinacquiring.com/services/crypto-friendly-payment-processing/)
    - Low cost SEPA transfers for Europe, SWIFT/wire transfers for outside the EU
    - Virtual IBAN Accounts- Set up unique IBAN account numbers for each of your clients
    - Not sure this does what we're looking for...
- [WireX](https://wirexapp.com/business/wirex-business)
    - I don't think this does what we're looking for...
- [CryptoProcessing](https://cryptoprocessing.io/api)
- [CryptoAPIs](https://cryptoapis.io/)

## Proposed Implementation
From @Phinneas
1. Create new page for payments. Client navigates there from landing-page
1. On new page dorg.tech/pay where clients can set-up payment, embed Wyre JSWidget
https://docs.sendwyre.com/docs/widget-api-2
1. From this page client would be sent to dOrg's DAO address to arrange payment.

## Funding
[[Proposal Passed](https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526/proposal/0x224980d17cb684f5076601d63384ce860c25009de831e35a660d6d86c3534cd1)] $1,000 US

**Comment by Phinneas** [comment]
I am looking to work on this as my first project.

**Comment by dOrgJelli** [comment]
Amazing! Some things we should iron out:
- What should the deliverable look like?
- What funding will the DAO commit to this?

@orishim @Phinneas @nickplace any thoughts?

**Comment by Phinneas** [comment]
**Description**
Create a fiat-on-ramp for those clients who do not use cryptocurrency. So new clients have the convenience of using bank transfers instead. 

**Potential Implementation**
Initial thoughts on implementation:
1) Create new page for payments. Client navigates there from landing-page
2) On new page dorg.tech/pay where clients can set-up payment, embed Wyre JSWidget
https://docs.sendwyre.com/docs/widget-api-2
3) From this page client would be sent to dOrg's DAO address to arrange payment.

**Funding**
$1,000 US

**Comment by dOrgJelli** [comment]
Amazing, thanks for this @Phinneas! I've added your details to the issues description above and created a proposal to the DAO to see if it'll commit to funding this: https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526/proposal/0x224980d17cb684f5076601d63384ce860c25009de831e35a660d6d86c3534cd1

**Comment by nickplace** [comment]
I use waveapps to collect fiat from clients. Works great and they have a gateway built in. They take around 7% though if I remember right. But I like wave because it sends automatic payment reminders, tracks clients, has exportable reports. I say don't reinvent the wheel. Maybe implement something like this: https://developers.paystack.co/reference

**Comment by dOrgJelli** [comment]
@nickplace we're looking for something that automatically converts fiat into crypto, I'm not sure waveapps or paystack do this after taking a quick glance?

**Comment by orishim** [comment]
@Phinneas proposal has passed!

**Comment by orishim** [comment]
Really cool tool for aggregating fiat on-ramps
https://github.com/dolomite-exchange/Fiat-Adapter

**Comment by willyogo** [comment]
Also recommend implementing Wyre's debit card feature. They don't have an embeddable version, but you can just pop open a new window and pass through query parameters such as the DAO's ETH address and accepted asset(s).

Docs: https://docs.sendwyre.com/docs/hosted-widget-1

Example 1: https://pay.sendwyre.com/purchase

Example 2: https://pay.sendwyre.com/purchase?destCurrency=DAI&dest=0xB5410de3c8Fe15872511eC8247EFd34CB8836A29
https://pay.sendwyre.com/purchase

Fees are 3.5% for debit, no account required (KYC is done in the background through debit card provider), and funds are received in minutes. Unfortunately there's a $250/day limit and I'm pretty sure it's US only at the moment. Really easy to implement though.

**Comment by nickplace** [comment]
@Phinneas Assuming this is abandoned.. I would liketo pick this up if so.

**Comment by Phinneas** [comment]
If possible I would like one more week or I could switch to something else.

**Comment by nickplace** [comment]
@Phinneas Feel free to look for an issue and create a proposal for it if you'd like. I did some digging around and it looks like every option supported by Dolomite is either not for US companies or requires a demo before signing up. Wyre doesn't support Virginia LLCs. Put a request into Moonpay and Carbon for a demo. Will update when I hear back.

**Comment by nickplace** [comment]
Should be pretty straightforward once we're approved by a provider or three.

- Create a page at dorg.tech/fiat with optional GET parameters: amount & message, which launches the dolomite modal and then displays a success or fail message.

We need to decide:

- What currency do we, by default, want to accept? (ETH, DAI, SAI?)
- What regions are we legally allowed to accept money from?
- Do we order providers by lowest selling fee (better for us) or lowest buying fee (better for client)

**Comment by Phinneas** [comment]
@nickplace there was a proposal that was funded. Did you look at that proposal?

**Comment by nickplace** [comment]
Carbon.money approved our account.. $2500 daily limit though so clients would need to pay over time. Still waiting to hear back from others.. @Phinneas any ideas?

**Comment by Phinneas** [comment]
@nickplace I would want to see what MoonPay has to say. There are also: https://cryptoapis.io or https://cryptoprocessing.io/api which might work as well. I don't think Carbon.money is a good option at this point unless over time the daily limit can increase.

**Comment by Phinneas** [comment]
What about this: https://www.kraken.com/en-us/features/funding-options

**Comment by Phinneas** [comment]
https://trade.kraken.com/markets?exchanges=kraken&types=spot%2Bfutures
https://support.kraken.com/hc/en-us/articles/360001449826-Deposit-and-withdrawal-limits-by-verification-level

And this from MoonPay: https://help.moonpay.io/en/articles/2509649-what-are-the-daily-and-monthly-limits

**Comment by orishim** [comment]
For Kraken I don't see an embeddable widget. And for MoonPay I don't see support for bank wires / ACH. 

The idea is that a customer can wire funds from their bank to a service that automatically converts it into crypto and sends it to the DAO.

Not sure if this is possible currently, but Wyre looks the most promising to me.

**Comment by orishim** [comment]
[Ramp](https://ramp.network/) looks like the winner! You can specify any eth address as the destination for the crypto purchased from the user's bank account.

- https://buy.ramp.network/?swapAsset=DAI&userAddress=0x15344EcDc2c4EDFCB092E284d93c20F0529FD8a6

You can do the same with credit/debit cards with Wyre:

- https://pay.sendwyre.com/purchase?destCurrency=DAI&paymentMethod=debit-card&dest=0x15344EcDc2c4EDFCB092E284d93c20F0529FD8a6

Wyre also has bank ACH support via Plaid but I didn't look into it yet
https://docs.sendwyre.com/

**Comment by Phinneas** [comment]
So is this back to Wyre then? Wyre, I've learned, is what Metamask uses, but their use case is a little different. 
Also @nickplace  had brought up some questions about this ticket such as 

What currency do we, by default, want to accept? (ETH, DAI, SAI?)
What regions are we legally allowed to accept money from?
Do we order providers by lowest selling fee (better for us) or lowest buying fee (better for client)

**Comment by Phinneas** [comment]
Description
Create a fiat-on-ramp for those clients who do not use cryptocurrency. So new clients have the convenience of using bank transfers instead.

Potential Implementation
Initial thoughts on implementation:

Create new page for payments. Client navigates there from landing-page
On new page dorg.tech/pay where clients can set-up payment, embed Wyre JSWidget
https://docs.sendwyre.com/docs/widget-api-2
From this page client would be sent to dOrg's DAO address to arrange payment.

**Comment by dOrgJelli** [comment]
Sounds like a great idea to me @Phinneas !
