### ISSUE TITLE
Admin Email Bots

### ISSUE THREAD

**Issue by orishim** [dOrgTech/Ecosystem#30]
# Description

A service that automates various administrative tasks that are time-consuming and repetitive through intelligent email notifications. Some respond to blockchain events and others to human input.

Here are some that would be very useful:

- **Payment Notifications**: Sends freelancers email notifications about payment and/or Rep proposals to them. Triggered by blockchain events (proposal submitted, proposal pass, proposal timeout)

- **Project Management**: Sends freelancers email reminders at set times before their project deadlines. Freelancers respond with updates, which are forwarded to the rest of the team on that project.
  - Inputs = Task breakdown by due dates and assigned freelancers

- **Invoicing**: Auto-generates and emails invoices to clients 1 week before payment due date, 5 days after due date (if payment not made), 10 days after (if payment still not made).
  - Inputs = Client's name, address, business I.D; Description of service; Payment Schedule

- **On-boarding**: After a new freelancer submits a successful bounty, send them a welcome message, link to dOrg handbook and auto-generated Term Sheet to sign.

- **Balanced Growth**: Sends out sales emails to potential clients and recruitment emails to potential freelancers when we need more of either.
  1. Interested clients and freelancers fill out intake form with embedded interview scheduler (calendly)
  2. After an interview with 2 dOrg members, clients and freelancers are sorted into respective priority queues
  3. When capacity (supply) exceeds project flow (demand), email next 5 clients in the client queue
  4. When project flow (demand) exceeds capacity (supply), email next 5 freelancers in the freelancer queue

# Impact
Automate the time-consuming administrative tasks of running a service-provision / work-allocation DAO. This could eventually be extended into a product that we offer to other DAOs.

**Comment by dOrgJelli** [comment]
Also think we should add "Notifications when the DAO receives a payment"

**Comment by dOrgJelli** [comment]
Another use-case is having an automated email for all dOrg members saying "here are the active projects, their budgets, and who's working on them". This way agents can see "oh, this project has a bunch of excess funds that haven't / won't be claimed because it's understaffed, let me hop on this and contact the lead."

**Comment by orishim** [comment]
Potentially useful:

https://www.notus.events/

" Notus is a service that allows users to trigger webhooks from Ethereum smart contract events or Graph Protocol GraphQL subscriptions."

**Comment by dOrgJelli** [comment]
Tried creating a simple notification using Notus for whenever the DAO has a proposal added, but I hit an error in their UI and cannot get past it. Will report back here when I hear back.

**Comment by dOrgJelli** [comment]
This is their response
> Hey @dOrgJelli - We've moved away from this project to focus on PoolTogether full-time and no longer have time to maintain Notus. There are bugs in it that we cannot tend to, however just last week we did open source the frontend and API server so anyone can run their own versions of Notus! https://github.com/DeltaCamp/notus-api and https://github.com/DeltaCamp/notus-frontend

> Some alternatives to Notus are https://matic.network/dagger - https://aleth.io/ - and Blocknative may even have something

**Comment by dOrgJelli** [comment]
Matic's Dagger API looks really cool, here's a code snippet for using it in JS:
```javascript
const GNTAddress = '0xa74476443119a942de498590fe1f2454d7d4ac0d';

// eth-dagger.js also provides web3 way to get parsed log
const web3Contract = new web3.eth.Contract(abi, GNTAddress);

// Get dagger contract
const daggerContract = dagger.contract(web3Contract);

// Get subscription filter
const filter = daggerContract.events.Transfer({filter: { from: '0x12345678....' }});

// Start watching logs
filter.watch((log) => {
  // log.returnValues.value => 100 GNT
  // log.returnValues.from => '0x12345678...'
  // log.returnValues.to => address which value has been transferred to
});
```

**Comment by orishim** [comment]
Also relevant:
https://terminal.co/
 https://docs.terminal.co/infrastructure-studio/overview
