### ISSUE TITLE
Proposal Template to use with Clients

### ISSUE THREAD

**Issue by orishim** [dOrgTech/Ecosystem#31]
A nice template with a cohesive, minimalistic branding and color scheme. The template would include some boilerplate like
- logo (upper left hand corner?)
- link to dOrg.tech (upper right hand corner?)

And then sections that we can fill in, such as:
- Client
- Overview
- Deliverables with duration and cost for each
- Total duration + Estimated delivery date
- Total cost

**Comment by orishim** [comment]
I've landed on a pretty good template for this, it just doesn't have any styling/color/branding.

Please reach out if you're interested in seeing.

**Comment by dOrgJelli** [comment]
@orishim nice! wanna upload to operations repo for safe keeping?

**Comment by orishim** [comment]
It's in our Notion. Sort of tricky to upload to operations because it is using some Notion-flavored markdown formatting. For now anyone can clone that.. better solutions welcome

**Comment by dOrgJelli** [comment]
Can you paste a link @orishim? Can't find it.

**Comment by orishim** [comment]
https://www.notion.so/dorg/Nectar-Auction-Proposal-28e1434d6802416db6ae140fd6bade73
