### ISSUE TITLE
Reputation-Weighted Payment Splitting

### ISSUE THREAD

**Issue by orishim** [dOrgTech/Ecosystem#32]
## Context
Currently all client payments are pooled in the dOrg DAO. Contributors must then submit  proposals to receive payments from the DAO on a regular basis. Each contributor accumulates Reputation (voting power) in proportion to cumulative payments earned.

## Description
Proposed change to dOrg's payment/Rep dynamics:

1. Rep is totally rebalanced to reflect each person's CURRENT contribution level (1-100) rather than cumulative/historical contributions 📊

2. Clients send payment to a reputation-weighted payment splitter, which instantly allocates the funds among Rep-holders 💸

3. The DAO itself also has a Rep score (say, 200). The DAO's portion of cashflows are allocated through proposals to cover overhead (benefits, bounties, software subscriptions, legal fees) and fund internal projects 📜

## Impact
- _Eliminate payment proposals_.
- _Hyper-align all active contributors_ around raising revenues & reducing overhead.
- _Decentralize load-balancing_: Each contributor has a direct incentive to make sure that we do not take on more projects than we can handle (since under-delivering would jeopardize future cashflows).
- _Incentivize performance_: If someone consistently over-delivers, we raise their proportion of cash flow by increasing their Rep– this dilutes everyone else in the short-term but should raise total cashflows in the long-term.
- _Disincentivize poor performance_: If someone consistently fails to deliver, we reduce their proportion of cash flow by slashing their Rep.

## Potential Implementation
The Solidity for this should be very simple. Some adaptation of OpenZeppelin's [Payment Splitter](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/payment/PaymentSplitter.sol) or @bogdanbatog's [dividend distribution contracts](https://github.com/dOrgTech/BC-DAO/tree/master/contracts/BondingCurve/dividend). 

## Future Directions
If this proves useful to us, it will probably work for other service businesses/DAOs as well. Here are some improvements we could make down the line:
- **User Interface** for claiming, monitoring and managing cashflow distributions.
- **Nesting** multiple splitters within one another would lead to federated, self-governing payment chains.
- **Interoperability**– support multiple DAO frameworks.
- **Smoothing** A tap could smooth out claimable amounts over time, rather than instantly splitting each payment.
- **Rate Limiting** @dOrgJelli suggested we add an upper bound on the payout per Rep-holder over a given unit of time, such as a `max_monthly_salary`.
- **Externally Derived Reputation** @dOrgJelli suggested we automate the calculation of contributor Rep scores from external metrics like Github activity (see [SourceCred](https://sourcecred.io/))

**Comment by orishim** [comment]
To preserve the tracking of cumulative/historical contributions, we could utilize dOrg’s native erc-20. Current Rep balances would determine initial token balances, and from there we continue minting to contributors at a rate of 1 token per $200 earned.

Down the line, we could explore benefits that are redeemable for these tradeable tokens, such as:
- Reimbursements for travel, co-working, health insurance and wellness expenses
    `1 token = $1 of travel = $1.50 of co-working = $2 of health insurance`...
- Access to scarce dOrg resources like living space or conference tickets
    `Maintain balance of >= 50 tokens for Devcon tickets`

**Comment by orishim** [comment]
Related #24

**Comment by jpkcambridge** [comment]
@orishim I think this is an intriguing proposal and an important problem to solve, essentially project management for DAOs.  I have a couple initial thoughts:

1) Maintaining an accurate balance of CURRENT contribution level might be as hard or harder than current administrative overhead.

2) I think as the organization grows, alignment of stake holders and individual incentives will be diluted as the proportional impact of an individual's effort on their own compensation decreases.  This could potentially be addressed in distribution of contribution level, but would increase the need for nuance there.  I wonder if there is a way to make the rules more "local," i.e. project specific, while loosely tying together the DAO as a whole.

**Comment by dOrgJelli** [comment]
My biggest critique of this is that: we have so many areas of optimization that we haven't explored yet, I don't know if this large of a shift in how we operate is necessary or pragmatic. For example, a lot of our problems could go away if we automate away / build tools for:
* Payment Proposals
* Weekly Project Updates
* Deadline Tracking
* Client Feedback
* Client Invoicing
* GitHub PR DAO Linking
* Onboarding Agents
* Agent Profiles + Project History
* Onboarding Client Projects + Assigning Agents to Projects

**Comment by orishim** [comment]
> Maintaining an accurate balance of CURRENT contribution level might be as hard or harder than current administrative overhead

In the current system each individual's contributions are documented, priced and voted on every two weeks for each of their projects. This process is highly bureaucratic, difficult to keep on track, and requires constant judgement calls.

This proposal is specifically about eliminating the need to price every bit of contribution. Instead, each member has a single value that's only changed when the group sees a sustained change in their contribution level. Maybe just as hard to get right, but certainly a lot less work!

> individual incentives will be diluted as the proportional impact of an individual's effort on their own compensation decreases... I wonder if there is a way to make the rules more "local," i.e. project specific, while loosely tying together the DAO as a whole.

Nesting could help groups to discover local optima organically. So a dOrg wide payment splitter, for instance, could send a portion of funds to a project-specific payment splitter.

**Comment by orishim** [comment]
ENS could greatly improve this sort of nesting extendability.

For example, the dOrg DAO could set the resolver of `dorg.eth` to our reputation-weighted payment splitter and direct clients to pay us there.

We can then set-up special purpose subdomains that point to other payment splitters, DAOs or EOAs:
- Client Projects
    - `graph.dorg.eth`
    - `deversifi.dorg.eth`

- Partnerships or Joint Ventures
    - `levelk.dorg.eth`
    - `underscore.dorg.eth`

- DAO members 
    - `orishim.dorg.eth`
    - ...

There would also be a U.I. to easily manage sub-domain and payment routing relationships.

**Comment by bogdanbatog** [comment]
We definitely have or can build the tools to automate more of dOrg's processes but automation is best used for repetitive, boring-repetitive actions. Whereas dOrg is currently experimenting with novel organization structures that have not really been tried before and this process is inherently iterative and includes a fair part of trial and error.

To improve upon it, i think we need to separate some high level business decisions from the technical means used to operate the organization. I could see at least the following key business needs that should be easy to address, no matter the technical means:
* ability to decide (by vote) % of monthly income that should go to treasury vs be allocated to the "salary fund"
* ability to increase/decrease the sales commission based on upcoming project pipeline (the same for recruiting new members)
* ability to change the compensation level of members
* ability to decide on taking a new customer/project

I like this PR proposal and I suggest these slight changes:
1) members should be able to choose their involvement level (100%, 50%, 25%, 0%), maybe monthly, and it should be factored in their payouts
2) I would replace the DAO rep score with a fixed percentage to make reasoning about it easier
3) this system should gradually, as the income flow stabilizes, evolve to one where member compensation is a fixed (even if low) monthly salary + % of monthly dOrg income

I agree that evaluating current contribution level could be as hard as current proposal system. But at least it could be done less frequent, maybe even once a quarter?

On the technical dividend implementation: i would love to have it put to real use but it's currently in a prototype stage and has not been used with real funds. If we proceed in this direction I would be more comfortable if we start by only funneling small amounts through it and gradually increase it.
