### ISSUE TITLE
Estimation for "Automatic GEN Reward" Feature

### ISSUE THREAD

**Issue by adrien-be** [dOrgTech/Ecosystem#35]
I'm considering posting a proposal on the Genesis DAO regarding getting a feature implemented. But before that I need an estimate on the cost for implementing it.

You can find the basic spec of that feature here: https://daotalk.org/t/automatic-gen-reward-to-proposals-that-pass/941

Happy to answer any question if that can help making that estimation easier.

**Comment by adrien-be** [comment]
For the record, Ori said:

"I wouldn’t say easy but it’s totally doable. You’d need a whole other scheme that has permissions to the DAO’s treasury to be able to send these bonuses out. It would be complicated imo"

**Comment by dOrgJelli** [comment]
Just responded @adrien-be https://daotalk.org/t/automatic-gen-reward-to-proposals-that-pass/941/2?u=dorgjelli

I think if it was a UI only implementation, it would be a small modification to Alchemy that would probably take a developer ~2-5 days to implement and get approved. Probably like 15-30 hours of time, so maybe like $1-2k? That's my ballpark at least.

**Comment by orishim** [comment]
Yeah I do not see a good reason to implement this on-chain since users can just ask for a GEN bonus with the existing Contribution Reward Scheme. I like the U.I. approach suggested by @dOrgJelli

**Comment by adrien-be** [comment]
Agreed, I suppose it's not the most urgent feature. 

Something that is a bit inconvenient right now though is that one cannot request both GEN and DAI because they are in the same field (dropdown).

![Screenshot 2019-11-28 16 08 45](https://user-images.githubusercontent.com/738533/69816814-6f4bf800-11f9-11ea-87ce-b0a43fea6b43.png)

**Comment by dOrgJelli** [comment]
Agreed @adrien-be, currently the ContributionReward scheme only supports one "external token" that can be rewarded for a given proposal. I've created this issue to request the feature of multiple external tokens be supported: https://github.com/daostack/arc/issues/693
