### ISSUE TITLE
Alchemy Mobile Styling Improvements/Fixes

### ISSUE THREAD

**Issue by mrrobot16** [dOrgTech/Ecosystem#52]
- Tooltip should either be removed or aligned properly in mobile
<img src="https://user-images.githubusercontent.com/761735/76713199-74c04600-66f5-11ea-89eb-05befd5df1cb.PNG" width="500"/>

- Size of menu item should be bigger
<img src="https://user-images.githubusercontent.com/761735/76713201-7558dc80-66f5-11ea-9952-852698cfab01.PNG" width="500"/>

- Size of menu item should be bigger and dao holdings should be better aligned
<img src="https://user-images.githubusercontent.com/761735/76713202-75f17300-66f5-11ea-852b-199c893dba17.PNG" width="500"/>

- Scheme cards border should be resized to fit mobile screens
<img src="https://user-images.githubusercontent.com/761735/76713203-75f17300-66f5-11ea-8d5d-a25a8c0a09e5.PNG" width="500"/>

- Proposal cards should be resized to fit mobile screens
<img src="https://user-images.githubusercontent.com/761735/76713204-768a0980-66f5-11ea-8471-03c62892312d.PNG" width="500"/>

- Params hash should be wrapped inside the box versus overflowing the box
<img src="https://user-images.githubusercontent.com/761735/76713205-768a0980-66f5-11ea-83b7-bde17a658f0c.PNG" width="500"/>

- There is a lot of dead space between the "New Genesis Protocol" button and the icon
<img src="https://user-images.githubusercontent.com/761735/76713208-7722a000-66f5-11ea-8ced-2016d0a38a45.PNG" width="500"/>

- Copy to Clipboard icons should fit inside the box
<img src="https://user-images.githubusercontent.com/761735/76713209-77bb3680-66f5-11ea-8a10-bd53a7d28699.PNG" width="500"/>

- To much dead space in my opinion here
<img src="https://user-images.githubusercontent.com/761735/76713211-7853cd00-66f5-11ea-9583-836aa08895c5.PNG" width="500"/>

- Either resize the box or make it so that copyclipboard and address/params hash fit the box
<img src="https://user-images.githubusercontent.com/761735/76713213-78ec6380-66f5-11ea-9669-7509a90519d2.PNG" width="500"/>

- Buttons should be aligned better
<img src="https://user-images.githubusercontent.com/761735/76713214-78ec6380-66f5-11ea-8ce2-8f490f4ed065.PNG" width="500"/>

- Text should fit inside the box
<img src="https://user-images.githubusercontent.com/761735/76713215-7984fa00-66f5-11ea-8123-09887131d9c8.PNG" width="500"/>

- Inputs should not be overflowed
<img src="https://user-images.githubusercontent.com/761735/76713216-7a1d9080-66f5-11ea-80e7-a58b8a715bcf.PNG" width="500"/>

- This is how it should fit in mobile versus the above
<img src="https://user-images.githubusercontent.com/761735/76713217-7a1d9080-66f5-11ea-9261-ba85b99c94e5.PNG" width="500"/>

- Tooltip for menu items should be positioned better 
<img src="https://user-images.githubusercontent.com/761735/76713218-7ab62700-66f5-11ea-97b3-fba2c977ef93.PNG" width="500"/>

- ProfileInfo Box should be resized to fit mobile screen
<img src="https://user-images.githubusercontent.com/761735/76787146-d5e82800-678e-11ea-9bd6-a3d91981a6a2.jpg" width="500"/>

**Comment by orishim** [comment]
Estimated time to make all these changes: 3 days

**Comment by orishim** [comment]
moved to [here](https://github.com/dOrgTech/Ecosystem/pull/59) as Alchemy RFC
